apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: backend-svc
    tier: frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    nodePort: 31000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: backend-svc
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-svc
        tier: frontend
    spec:
      containers:
        - name: react-client
          image: mishramayankk20/mod_react:99
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      restartPolicy: Always
# kind: Service
# apiVersion: v1
# metadata:
#   name: react-client
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 80
#       protocol: TCP
#       nodePort: 31000
#   selector:
#     app: nodejs-server
# ---
# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   name: react-client
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: nodejs-server
#   template:
#     metadata:
#       labels:
#         app: nodejs-server
#     spec:
#       containers:
#         - name: react-client
#           image: mishramayankk20/react_docker:123
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 80
#       restartPolicy: Always