
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  selector:
    app: backend-svc
    tier: backend
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend-svc
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-svc
        tier: backend
        track: stable
    spec:
      containers:
        - name: nodeimage
          image: mishramayankk20/mod1_server:99
          ports:
            - name: http
              containerPort: 5000
      restartPolicy: Always
# apiVersion: v1
# kind: Service
# metadata:
#   name: nodejs-server
# spec:
#   selector:
#     app: nodejs-server
#   ports:
#     - protocol: TCP
#       port: 5000
#       targetPort: 5000
#   type: NodePort
# ---      
# apiVersion: apps/v1 
# kind: Deployment 
# metadata: 
#   name: nodejs-server 
# spec: 
#   replicas: 1
#   selector: 
#     matchLabels: 
#       app: nodejs-server 
#   template: 
#     metadata: 
#       labels: 
#         app: nodejs-server
#     spec: 
#       containers:
#       - name: nodeimage
#         image: mishramayankk20/nodejs_server:22
#         ports: 
#         - containerPort: 5000
    
#http://172.20.0.3:31000/